decluttering_templates:
  !include lovelace/user_templates/user_templates.yaml

sak_sys_templates:
  !include www/community/swiss-army-knife-card/sak_templates.yaml

sak_user_templates:
  !include lovelace/sak_templates/sak_templates.yaml

resources:
  - type: js
    url: /local/custom-brand-icons.js

views:
  - !include lovelace/all_in_one.yaml
  - !include lovelace/pogoda.yaml
  - !include lovelace/sensor.yaml
  - !include lovelace/switch.yaml
  - !include lovelace/header_room.yaml
