homeassistant:
#   name: Мой дом
  latitude: 55.431310
  longitude: 65.340229
  elevation: 80
  unit_system: metric
  time_zone: Asia/Yekaterinburg
  packages: !include_dir_merge_named includes/packages

default_config:

frontend:
    themes: 
        day_and_night:
            primary-color: '#055BFA'
            ha-card-border-width: 0px
            modes:
                light:
                    primary-background-color: '#F2F2F2'
                    theme-scale:              '#D0D0D0'
                dark:
                    primary-background-color: '#282828'
                    theme-scale:              '#3D3D3D'

lovelace:
    mode: yaml
    resources:

      - url: /local/sys-card/decluttering-card.js
        type: module

      - url: /local/sys-card/user-card.js
        type: module
      
#      - url: /local/sys-card/sys-card.js
#        type: module

      - url: /local/community/mini-graph-card/mini-graph-card-bundle.js
        type: module
    
      - url: /local/community/button-card/button-card.js
        type: module

      - url: /local/community/lovelace-layout-card/layout-card.js
        type: module

      - url: /local/community/mini-media-player/mini-media-player-bundle.js
        type: module

      - url: /local/community/lovelace-digital-clock/digital-clock.js
        type: module

      - url: /local/community/clock-weather-card/clock-weather-card.js
        type: module     

      - url: /local/community/lovelace-mushroom/mushroom.js
        type: module
    
      - url: /local/community/stack-in-card/stack-in-card.js
        type: module
    
      - url: /local/community/apexcharts-card/apexcharts-card.js
        type: module
      
      - url: /local/community/lovelace-card-mod/card-mod.js
        type: module  

      - url: /local/community/text-divider-row/text-divider-row.js
        type: module

# yandex_station:
#   username: kkaapp
#   password: Ghbynth&6


input_boolean: !include includes/input_boolean.yaml
script: !include_dir_merge_named includes/scripts
automation: !include_dir_merge_list includes/automations

